from __future__ import annotations

from app import db
from app.models import Book, BookChapter, BookChapterRevision
from app.services.publishing_service import ensure_chapter_workflow_seed


def migrate_reader_sections_to_chapter_revisions(*, book_id: int | None = None, dry_run: bool = False):
    """
    Backfill chapter workflow tables from existing published reader content.
    """
    query = Book.query
    if book_id:
        query = query.filter(Book.id == int(book_id))
    books = query.order_by(Book.id.asc()).all()

    migrated = 0
    skipped = 0
    for book in books:
        if BookChapter.query.filter_by(book_id=book.id).first():
            skipped += 1
            continue
        ensure_chapter_workflow_seed(book)
        migrated += 1

    if dry_run:
        db.session.rollback()
    else:
        db.session.commit()
    return {'migrated_books': migrated, 'skipped_books': skipped, 'dry_run': bool(dry_run)}


def rollback_chapter_migration(*, book_id: int | None = None):
    """
    Roll back chapter workflow records generated by migration.
    ReaderSection / ReaderParagraph published content is kept untouched.
    """
    chapter_query = BookChapter.query
    revision_query = BookChapterRevision.query
    if book_id:
        chapter_query = chapter_query.filter(BookChapter.book_id == int(book_id))
        revision_query = revision_query.join(BookChapter, BookChapter.id == BookChapterRevision.chapter_id).filter(
            BookChapter.book_id == int(book_id)
        )

    chapter_ids = [row.id for row in chapter_query.all()]
    if chapter_ids:
        BookChapterRevision.query.filter(BookChapterRevision.chapter_id.in_(chapter_ids)).delete(synchronize_session=False)
    chapter_query.delete(synchronize_session=False)
    db.session.commit()
    return {'rolled_back_chapters': len(chapter_ids), 'book_id': int(book_id) if book_id else None}
